```{r}
library("gridExtra")
library("tidyverse")
library("ggplot2")
library("highcharter")
```

---
Hackathon
Monday, February 24

Dataset: World Happiness Report Datasets (2019)
---

First grab the data.

```{r}
df_2019 <- read.csv("/Users/lubis/Documents/study/dataanalysis/hackathon/world-happiness/2019.csv", header=TRUE)
df_2015 <- 
  read.csv("/Users/lubis/Documents/study/dataanalysis/hackathon/world-happiness/2015.csv", header=TRUE) %>%
  select(Country, Region)
```

Check types of each column

```{r}
str(df_2019)
str(df_2015)
```

```{r}
df_2019 <- rename(df_2019, Country = Country.or.region)
```

```{r}
str(df_2019)
str(df_2015)
```

```{r}
df_2019 <- left_join(df_2019, df_2015)
```

- Playing with plotting between variables and happiness score

```{r}
columns <- c("GDP.per.capita", "Social.support", "Healthy.life.expectancy",
             "Freedom.to.make.life.choices", "Generosity", "Perceptions.of.corruption")
p1 <- ggplot(data = df_2019, mapping = aes(x = !!sym(columns[1]) , y = Score)) +
       geom_point(aes(alpha = 0.5, color = Region), show.legend=FALSE) +
       geom_smooth(method = "lm") + theme(legend.title = element_blank())
p2 <- ggplot(data = df_2019, mapping = aes(x = !!sym(columns[2]) , y = Score)) +
       geom_point(aes(alpha = 0.5, color = Region), show.legend=FALSE) +
       geom_smooth(method = "lm") + theme(legend.title = element_blank())
p3 <- ggplot(data = df_2019, mapping = aes(x = !!sym(columns[3]) , y = Score)) +
       geom_point(aes(alpha = 0.5, color = Region), show.legend=FALSE) +
       geom_smooth(method = "lm") + theme(legend.title = element_blank())
p4 <- ggplot(data = df_2019, mapping = aes(x = !!sym(columns[4]) , y = Score)) +
       geom_point(aes(alpha = 0.5, color = Region), show.legend=FALSE) +
       geom_smooth(method = "lm") + theme(legend.title = element_blank())
p5 <- ggplot(data = df_2019, mapping = aes(x = !!sym(columns[5]) , y = Score)) +
       geom_point(aes(alpha = 0.5, color = Region), show.legend=FALSE) +
       geom_smooth(method = "lm") + theme(legend.title = element_blank())
p6 <- ggplot(data = df_2019, mapping = aes(x = !!sym(columns[6]) , y = Score)) +
       geom_point(alpha = 0.5, aes(color = Region), show.legend=FALSE) +
       geom_smooth(method = "lm") 

grid.arrange(p1, p2, p3, p4, p5, p6, nrow=3, heights=c(4,4,4))
```

- Mean income against mean score

```{r}
mean <- ggplot(
  df_2019 %>%
    group_by(Region) %>%
    summarise(mean_score = mean(Score),
              mean_income = mean(GDP.per.capita)),
  mapping = aes(x = mean_income, y = mean_score)) +
    geom_point(aes(color=Region))

box <- ggplot(df_2019,
       aes(x = Region, y = Score, colour= Region)) +
      geom_point(alpha = 0.7) +
      geom_boxplot(alpha = 0, colour = "black")

grid.arrange(mean, box, ncol=2)
```


```{r}
cor <- cor(df_2019[,c(3,4,5,6,7,8,9)])
```

```{r}
library(reshape2)
map_cor <- melt(cor)
ggplot(data = map_cor, aes(x=Var1, y=Var2, fill=value)) + geom_tile() + 
  scale_fill_gradient(low="white", high="red")
```

```{r}
data(worldgeojson, package = "highcharter")

countries <- df_2019 %>% 
  filter(!is.na(Country)) %>% 
  select(Country, Score)

highchart() %>%
hc_add_series_map(worldgeojson, countries, value = "Score", joinBy = c('name','Country'))  %>% 
    hc_colors(c("darkorange", "darkgray")) %>% 
    hc_colorAxis(stops = color_stops(), min=2.5, max=8) %>% 
    hc_title(text = "Happiness Score")
```

```{r}
library(plotly)

p <- df_2019 %>%
  ggplot(aes(GDP.per.capita, Score, color=Region)) +
  geom_point() +
  theme_bw()

ggplotly(p)
```

