---
title: "6thMeeting-SemiHackathon Session"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**6thMeeting - Monday, February 24, 2020**

This is the first trial of hackathon, thus we will call "Semi" Hackathon. 
No pressure, the main point is having fun. We encourage each participant to set your own target and let's help each others!

## Target

1. Data exploratory (main target: data wrangling, ploting distribution, and descriptive statistic)
2. Simple statistic inference (optional: if you interested in certain case)
3. Possible analysis (what analysis is needed to get more informations out of the data)
4. Short report (if time permit)


## Datasets

If you have your own dataset to solve, please come with it.
If you prefer to explore same dataset together, let's use this [World Happiness Report Datasets](https://www.kaggle.com/unsdsn/world-happiness). Full report can be found in the [World Happiness Report website](https://worldhappiness.report/).

Below is the list of examples on how to explore the data, for your inspiration.

* From kaggle: [Kaggle Kernels](https://www.kaggle.com/unsdsn/world-happiness/kernels)

* From Rpubs: [Elissa, et al 2018](https://rpubs.com/koki25ando/DATA1001TeamBver1) and [Prakki Rama, 2019](https://rpubs.com/Prakki_Rama/whd)

Example of problem set for data exploration:

1. What countries or regions rank the highest in overall happiness and each of the six factors contributing to happiness?
2. How did country ranks or scores change between the 2015 and 2016 as well as the 2016 and 2017 reports?
3. Did any country experience a significant increase or decrease in happiness?
4. What are the different factors that lead to happiness of a country?
5. What similarities and differences do the countries experiencing the highest/lowest WHS have?
6. Does being in a certain region [continent] have any correlation to the average score of countries?
7. What role does the economy play in determining the happiness of a country?
8. Which factor, on average, contributes most/least to happiness?

Exploring about Indonesia's ranks or scores change between the 2015 and 2016 as well as the 2016 and 2017 would be interesting. We also can compare Indonesian's conditions with other country(ies) of interest. 

What about some other comprehensive picture? If you familiar with the [Factfulness book](https://www.gapminder.org/factfulness-book/), you may now about the [Gapminder datasets](https://www.gapminder.org/data/) with its famous buble scatterplot. Some interesting analysis can be found [here](https://www.gapminder.org/tools/).

Below are some inspirations on where we can go from gapminder datasets:

1. https://towardsdatascience.com/exploratory-data-analysis-in-r-of-global-data-from-gapminder-13c5de5bee70
2. https://cran.r-project.org/web/packages/gapminder/README.html
3. http://euclid.psych.yorku.ca/www/psy6135/tutorials/gapminder.html

Let's discuss together about what problem set we want to dive in. Each person can have different goals. 

## Hackathon format

We will start the hackhaton with the introductions about datasets and what problem we want to solve/learn. If you bring your own datasets, please introduce it as well. In the end of the day, we hopefully can conclude our today's session with the short notes from each of participant and evaluate about should we do this kind of activity again?

**Schedule at glance**:

**11.00-11.45 Data introduction, listing Problem to solve, notes on R markdown**
  
Here, we will get to know abut the data and build the problem to solve. If you bring your own datasets, please introduce it as well. For those who want to make notes in R markdown, there will be brief explanation about that. You can also use jupyter notebook for taking the notes. Both R markdown and Jupyter notebook will let you create your notes with the code embeded on that.

**11.45-12.45  Break (ISHOMA, let's buy pizza or any suggestion?)**

Prayer and lunch time. 

**12.45-14.30 Hack Hack!**

Get's your hands (and laptop) ready for data exploration. Raise your hand or discuss with friend if you get some problem. 
Roles: If you can't move on within 10 minutes with your code, it's time to ask for help. 


**14.30-15.00 Checkpoint 1 (discussion)**

How's the coding going? Have you reach 50% of your target? What's interesting thing you have learn or find? Do you have hard time in this practice?

**15.00-15.30 Break**

Prayer time and probably you need coffee at this point (or short nap?)

**15.30-17.00 Hack Hack!**

Continue! Remember the roles: If you can't move on within 10 minutes with your code, it's time to ask for help. 

**17.00-17.30 Checkpoint 2 (discussion + conclusion)**

What some interesting things you've learn? Do you get interesting  informations from the data?
Have you reach the targets? 

**17.30-18.00  Evaluation, Impression, Where should we go from this?**

How's the day? Is it fun? too difficult? Challenging? Should we do this kind of activity again
Please share your notes on our github or other platform. Or someone probably want to write article about this?

**18.00- End of Hackhaton, let's have dinner together!**


## Notes of the activity

### Checkpoint 1

#### Jordy

Focus on year (2019):
Plot with bokeh--> with hover info for interactive plot. In R you can use `Plotly` or ..
From the data we can see the distribution of each factor for each country, region, subregion. 

See the notes here...

#### Al

Presentation about Anime recomendation.
For the recommender system based on rate of each anime. 
The analysis consists of:
1. Data filtering based on rates
2. Co-occurence metric for each anime

Final output will be how close each anime with others, and knowing the pattern of watching.
See the notes here..


#### Era

Temporal analysis for Indonesia and how it compared to the southeast asia


#### Lutfhan

Focus on year 2019
Learning the ggplot
1. regression of each factor to happiness score
2. correlations of each

See notes here..

#### Felix

Data wrangling adding region into the dataframe.
Visualization of each factor into the violin plot
Vizualisations of correlations between score and each score for each regiomn
See notes here...


### Checkpoint 2

#### Luthfan and Felix

Package "highcharter" for vizualizations of happiness score in worldmap.
Combine all tables in different timeline.

#### Jordhy

Map world happiness
Dataframe in geopandas, read by geo.json and plotted in bokeh. 


#### Era

Cleaning dataset. 

#### Fajar

Analysis per continent.

#### Mia




